# Generated by Django 3.2 on 2023-10-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
