# Generated by Django 4.2.5 on 2023-09-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="college",
            field=models.CharField(
                choices=[
                    ("교육관", "교육관"),
                    ("대강당", "대강당"),
                    ("신세계관", "신세계관"),
                    ("생활관", "생활관"),
                    ("정문", "정문"),
                    ("포스코관", "포스코관"),
                    ("학문관", "학문관"),
                    ("휴웃길", "휴웃길"),
                    ("잔디광장", "잔디광장"),
                    ("학문관광장", "학문관광장"),
                    ("스포츠트랙", "스포츠트랙"),
                ],
                max_length=20,
            ),
        ),
    ]
