# Generated by Django 4.2.5 on 2023-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_alter_event_college"),
    ]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="time",
            field=models.TextField(null=True),
        ),
    ]
