# Generated by Django 4.2.5 on 2023-09-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_alter_time_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="time",
            old_name="time",
            new_name="finishtime",
        ),
        migrations.AddField(
            model_name="time",
            name="starttime",
            field=models.TextField(blank=True, null=True),
        ),
    ]
