# Generated by Django 3.2 on 2023-10-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_rename_time_time_finishtime_time_starttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ManyToManyField(related_name='menu_items3', to='event.Event'),
        ),
        migrations.AddField(
            model_name='menu',
            name='college',
            field=models.ManyToManyField(related_name='menu_items2', to='event.Event'),
        ),
        migrations.AddField(
            model_name='menu',
            name='day',
            field=models.ManyToManyField(related_name='menu_items', to='event.Day'),
        ),
    ]
