# Generated by Django 3.2 on 2023-10-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20231004_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='college',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='day',
        ),
    ]
